site_name: Islandora 8
site_dir: site
docs_dir: docs
site_description: Documentation for Islandora 8

dev_addr: 'localhost:8111'
repo_url: https://github.com/Islandora/documentation

theme:
  name: 'material'
  palette:
    primary: 'red'
    accent: 'red'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  logo: 'assets/claw.png'
  language: 'en'
markdown_extensions:
  - admonition

extra:
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  author:
    twitter: 'islandora'
  palette:
    primary: 'red'
    accent: 'red'
  logo: 'assets/claw.png'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/islandora'

nav:
  - Summary: 'index.md'
  - Installation: 'installation.md'
  - User Documentation:
      - 'Introduction': 'user-documentation/user-intro.md'
      - 'Resource Nodes': 'user-documentation/resource-nodes.md'
      - 'From Objects to Resource Nodes': 'user-documentation/objects_to_resource_nodes.md'
      - Media:
          - 'Add Media': 'user-documentation/media.md'
          - 'Add Video': 'user-documentation/adding-video.md'
          - 'Add Audio': 'user-documentation/adding-audio.md'
      - 'Create a Resource Node': 'user-documentation/creating-a-node.md'
      - 'Collections': 'user-documentation/collections.md'
      - 'Paged Content': 'user-documentation/paged-content.md'
      - 'Metadata': 'user-documentation/metadata.md'
      - 'Content Types': 'user-documentation/content_types.md'
      - 'Searching': 'user-documentation/searching.md'
      - 'Context': 'user-documentation/context.md'
      - 'Views': 'user-documentation/create_update_views.md'
      - 'Users': 'user-documentation/users.md'
      - 'Blocks': 'user-documentation/blocks.md'
      - 'Usage Stats': 'user-documentation/usage-stats.md'
      - 'Multilingual': 'user-documentation/multilingual.md'
      - 'Accessibility': 'user-documentation/accessibility.md'
      - 'Extending Islandora': 'user-documentation/extending.md'
      - 'IIIF': 'user-documentation/iiif.md'
      - 'OAI-PMH': 'user-documentation/oai.md'
  - Repository Administrator Documentation:
      - 'RDF Generation': 'islandora/rdf-mapping.md'
  - System Administrator Documentation:
    - 'Installing Modules': 'technical-documentation/install-enable-drupal-modules.md'
    - 'Updating Drupal': 'technical-documentation/updating_drupal.md'
  - Developer Documentation:
    - REST Documentation:
      - 'Introduction': 'technical-documentation/using-rest-endpoints.md'
      - 'GET': 'technical-documentation/rest-get.md'
      - 'POST/PUT': 'technical-documentation/rest-create.md'
      - 'PATCH': 'technical-documentation/rest-patch.md'
      - 'DELETE': 'technical-documentation/rest-delete.md'
      - 'Signposting': 'technical-documentation/rest-signposting.md'
    - 'Running Tests': 'technical-documentation/running-automated-tests.md'
    - 'Flysystem': 'technical-documentation/flysystem.md'
    - 'JWT Authentication': 'technical-documentation/jwt.md'
    - 'Versioning Policy': 'technical-documentation/versioning.md'
    - 'How to Build Documentation': 'technical-documentation/docs-build.md'
    - 'Testing Notes': 'technical-documentation/testing-notes.md'
    - 'Adding back ?_format=jsonld': 'technical-documentation/adding_format_jsonld.md'
    - 'Updating a `deb` and adding it to Lyrasis PPA': 'technical-documentation/ppa-documentation.md'
    - 'Alpaca Tips': 'technical-documentation/alpaca_tips.md'

  - Migration:
      - 'CSV': 'technical-documentation/migrate-csv.md'
      - 'Islandora 7': 'technical-documentation/migrate-7x.md'
  - Contributing:
      - 'How to contribute': 'contributing/CONTRIBUTING.md'
      - 'Documentation Style Guide': 'contributing/docs_style_guide.md'
      - 'Committers': 'contributing/committers.md'
  - Glossary: 'user-documentation/glossary.md'
